// apps/react-app/src/components/layout/AppFooter.jsx
/**
 * AppFooter — 底部列
 */

function AppFooter() {
  return (
    <footer
      className="border-t py-3"
      style={{
        background: 'var(--bg-card)',
        borderColor: 'var(--border)',
      }}
    >
      <p className="text-center text-xs m-0" style={{ color: 'var(--text-muted)' }}>
        K-Pop Hub — 探索你喜愛的 K-pop 團體
      </p>
    </footer>
  )
}

export default AppFooter

// apps/vue-app/src/components/common/AppFooter.vue
<script setup>
// Footer 組件
</script>

<template>
  <q-footer elevated class="bg-sys-card border-t border-sys-border">
    <q-toolbar class="min-h-[44px]">
      <q-toolbar-title class="text-center text-xs text-textMuted">
        K-Pop Hub — 探索你喜愛的 K-pop 團體
      </q-toolbar-title>
    </q-toolbar>
  </q-footer>
</template>
