// apps/vue-app/src/pages/GroupPage.vue
<script setup>
import MemberCard from '@/components/member/MemberCard.vue'
import { getCompanyById, getGroupById, getMembersByGroup } from '@/data/kpop.js'

const route = useRoute()
const router = useRouter()

const group = computed(() => getGroupById(route.params.id))
const company = computed(() => group.value ? getCompanyById(group.value.companyId) : null)
const members = computed(() => group.value ? getMembersByGroup(group.value.id) : [])

watchEffect(() => {
  if (group.value === undefined)
    router.replace({ name: 'Home' })
})

function goToMember(memberId) {
  router.push({ name: 'Member', params: { id: memberId } })
}
</script>

<template>
  <div v-if="group" class="flex justify-center min-h-full -mx-4 -mt-4">
    <div class="w-full max-w-[480px] pb-6">
      <!-- Hero 封面圖 -->
      <div class="relative h-[220px] overflow-hidden">
        <img
          v-if="group.cover"
          :src="group.cover"
          :alt="group.name"
          class="w-full h-full object-cover"
        >
        <div
          v-else
          class="w-full h-full"
          :style="{ background: `linear-gradient(135deg, ${group.gradientFrom || '#1e1b4b'}, ${group.gradientTo || '#312e81'})` }"
        />
        <div class="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent" />

        <div class="absolute bottom-4 left-4 right-4">
          <p v-if="company" class="text-white/60 text-xs m-0 mb-0.5">
            {{ company.name }}
          </p>
          <h1 class="text-white text-2xl font-bold m-0 leading-tight">
            {{ group.name }}
          </h1>
          <p class="text-white/70 text-sm m-0 mt-0.5">
            {{ group.koreanName }}
          </p>
        </div>
      </div>

      <!-- Info Chips -->
      <div class="flex flex-wrap gap-2 px-4 py-3 border-b border-sys-border">
        <span
          class="inline-flex items-center gap-1 text-xs font-medium px-3 py-1 rounded-full"
          :style="{ background: `${group.color}22`, color: group.color }"
        >
          <q-icon name="favorite" size="0.75rem" />
          {{ group.fandomName }}
        </span>
        <span class="inline-flex items-center gap-1 text-xs px-3 py-1 rounded-full bg-sys-raised text-textSecondary">
          <q-icon name="calendar_today" size="0.75rem" />
          出道 {{ group.debut }}
        </span>
        <span class="inline-flex items-center gap-1 text-xs px-3 py-1 rounded-full bg-sys-raised text-textSecondary">
          <q-icon name="group" size="0.75rem" />
          {{ members.length }} 位成員
        </span>
      </div>

      <!-- 簡介 -->
      <div class="px-4 pt-3 pb-4 border-b border-sys-border">
        <p class="text-textSecondary text-sm leading-relaxed m-0">
          {{ group.description }}
        </p>
      </div>

      <!-- 成員列表 -->
      <div class="px-4 pt-4">
        <h2 class="text-textBase text-sm font-bold mb-4 m-0">
          成員
        </h2>
        <div
          class="grid gap-4"
          :class="members.length <= 4 ? 'grid-cols-4' : members.length <= 6 ? 'grid-cols-3' : 'grid-cols-4'"
        >
          <MemberCard
            v-for="member in members"
            :key="member.id"
            :member="member"
            :clickable="true"
            @click="goToMember"
          />
        </div>
      </div>
    </div>
  </div>
</template>

// apps/react-app/src/pages/GroupPage.jsx
/**
 * GroupPage — 團體詳情頁
 *
 * ── Vue 對比 ──────────────────────────────────────────────────
 * Vue：const route = useRoute()；route.params.id
 * React：const { id } = useParams()（直接解構）
 *
 * Vue：watchEffect(() => { if (!group.value) router.replace({ name: 'Home' }) })
 * React：useEffect(() => { if (!group) navigate('/', { replace: true }) }, [group, navigate])
 *
 * Vue：v-if="group"（條件渲染）
 * React：if (!group) return null（早期返回，更直觀）
 * ──────────────────────────────────────────────────────────────
 */

import { useEffect, useMemo } from 'react'
import { useNavigate, useParams } from 'react-router'
import { motion } from 'framer-motion'
import MemberCard from '@/components/member/MemberCard'
import { getCompanyById, getGroupById, getMembersByGroup } from '@/data/kpop'

function GroupPage() {
  const { id } = useParams()
  const navigate = useNavigate()

  const group = useMemo(() => getGroupById(id), [id])
  const company = useMemo(() => group ? getCompanyById(group.companyId) : null, [group])
  const members = useMemo(() => group ? getMembersByGroup(group.id) : [], [group])

  useEffect(() => {
    if (group === undefined) {
      navigate('/', { replace: true })
    }
  }, [group, navigate])

  if (!group) return null

  const gridCols = members.length <= 4 ? 'grid-cols-4' : members.length <= 6 ? 'grid-cols-3' : 'grid-cols-4'

  return (
    <motion.div
      className="flex justify-center min-h-full -mx-4 -mt-4"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.3 }}
    >
      <div className="w-full max-w-[480px] pb-6">
        <div className="relative h-[220px] overflow-hidden">
          {group.cover
            ? <img src={group.cover} alt={group.name} className="w-full h-full object-cover" />
            : (
                <div className="w-full h-full"
                  style={{ background: `linear-gradient(135deg, ${group.gradientFrom || '#1e1b4b'}, ${group.gradientTo || '#312e81'})` }}
                />
              )}
          <div className="absolute inset-0" style={{ background: 'linear-gradient(to top, rgba(0,0,0,0.85), rgba(0,0,0,0.2) 50%, transparent)' }} />

          <div className="absolute bottom-4 left-4 right-4">
            {company && <p className="text-white/60 text-xs m-0 mb-0.5">{company.name}</p>}
            <h1 className="text-white text-2xl font-bold m-0 leading-tight"
                style={{ fontFamily: 'var(--font-display)', letterSpacing: '0.05em' }}>
              {group.name}
            </h1>
            <p className="text-white/70 text-sm m-0 mt-0.5">{group.koreanName}</p>
          </div>
        </div>

        <div className="flex flex-wrap gap-2 px-4 py-3 border-b" style={{ borderColor: 'var(--border)' }}>
          <span className="inline-flex items-center gap-1 text-xs font-medium px-3 py-1 rounded-full"
                style={{ background: `${group.color}22`, color: group.color }}>
            ♡ {group.fandomName}
          </span>
          <span className="inline-flex items-center gap-1 text-xs px-3 py-1 rounded-full"
                style={{ background: 'var(--bg-raised)', color: 'var(--text-secondary)' }}>
            📅 出道 {group.debut}
          </span>
          <span className="inline-flex items-center gap-1 text-xs px-3 py-1 rounded-full"
                style={{ background: 'var(--bg-raised)', color: 'var(--text-secondary)' }}>
            👥 {members.length} 位成員
          </span>
        </div>

        <div className="px-4 pt-3 pb-4 border-b" style={{ borderColor: 'var(--border)' }}>
          <p className="text-sm leading-relaxed m-0" style={{ color: 'var(--text-secondary)' }}>
            {group.description}
          </p>
        </div>

        <div className="px-4 pt-4">
          <h2 className="text-sm font-bold mb-4 m-0" style={{ color: 'var(--text-base)' }}>成員</h2>
          <div className={`grid gap-4 ${gridCols}`}>
            {members.map(member => (
              <MemberCard
                key={member.id}
                member={member}
                clickable
                onClick={(memberId) => navigate(`/member/${memberId}`)}
              />
            ))}
          </div>
        </div>
      </div>
    </motion.div>
  )
}

export default GroupPage
